name: courses_app
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  device_preview: ^1.2.0
  animate_do: ^3.3.4
  animated_introduction: ^1.0.4
  flutter_svg: ^2.0.10+1
  pinput: ^5.0.0
  flutter_xlider: ^3.5.0
  get_it: ^7.7.0
  video_player: ^2.9.1
  flutter_slidable: ^3.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/
    - assets/svg_icons/auth/
    - assets/svg_icons/cateogry/
    - assets/svg_icons/main/
    - assets/svg_icons/courses_details/
    - assets/svg_icons/search/
    - assets/svg_icons/video_controller/
